package com.faculdade.computacaografica.lab1;

import java.awt.*;
import javax.swing.*;

public class PainelGato extends JPanel {


    public PainelGato() {
        initComponents();
    }
    
    @Override
    public void paint(Graphics g) {
        g.setColor(Color.black);
        g.drawRect(50, 50, 60, 60); // Cabeça
        g.drawRect(80, 225, 140, 5); // Cauda
        g.setColor(Color.white);
        g.fillOval(20, 110, 120, 120); // corpo é um circulo branco
        g.setColor(Color.black);
        g.drawOval(20, 110, 120, 120); // circunferencia do corpo em preto
        g.fillOval(75, 75, 10, 10); // nariz
        g.setColor(Color.blue);
        g.fillOval(60, 60, 10, 10); // olhos
        g.fillOval(90, 60, 10, 10);
        g.setColor(Color.black);
        g.drawLine(50, 50, 60, 30); // orelhas
        g.drawLine(60, 30, 70, 50);
        g.drawLine(110, 50, 100, 30);
        g.drawLine(100, 30, 90, 50);
        g.setColor(Color.red);
        g.drawArc(60, 80, 40, 20, 180, 180); // Boca
        g.setColor(Color.black);
        Font serif = new Font("Serif", Font.BOLD, 18);
        g.setFont(serif);
        g.drawString("Gato Java", 200, 50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
