package com.faculdade.computacaografica.lab1;

import java.awt.*;
import java.awt.image.ImageObserver;
import java.text.AttributedCharacterIterator;

import javax.swing.*;

public class PainelCarro extends javax.swing.JPanel {

    
    public PainelCarro() {
        initComponents();
    }
    
    @Override
    public void paint(Graphics g) {
        g.setColor(Color.blue);
        g.drawRect(100, 150, 200, 80); //Base do carro
        g.drawRect(140, 110, 120, 40); //Parte de cima do carro
        g.fillOval(120, 230, 20, 20); //roda esquerda
        
        g.fillOval(250, 230, 20, 20); //roda direita
        
        g.drawLine(125, 240, 135, 240); // orelhas
        g.drawLine(125, 240, 130, 235);
        g.drawLine(135, 240, 130, 235);
        
        g.drawLine(255, 240, 265, 240); // orelhas
        g.drawLine(255, 240, 260, 235);
        g.drawLine(265, 240, 260, 235);

        
        g.setColor(Color.black);
        g.drawLine(270, 135, 300, 100);
        Font serif = new Font("Serif", Font.BOLD, 18);
        g.setFont(serif);
        g.drawString("Carro Java", 300, 100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        
//       
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
